version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postsnet-postgres
    environment:
      POSTGRES_DB: Postsnet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: um17tzno
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: postsnet-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postsnet:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"

volumes:
  postgres-data:
  minio-data: